### ISSUE TITLE
I am getting Error EOF while parsing a value

### ISSUE THREAD

**Issue by BudiNverse** [BudiNverse/lta-rs#1]
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Json(Error("EOF while parsing a value", line: 1, column: 0)), url: None }', src\libcore\result.rs:1009:5
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libstd\sys\windows\backtrace\mod.rs:104
   1: std::sys::windows::backtrace::set_frames
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libstd\sys\windows\backtrace\mod.rs:104
   2: std::sys::windows::backtrace::set_frames
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libstd\sys\windows\backtrace\mod.rs:104
   3: std::sys_common::backtrace::print
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libstd\sys_common\backtrace.rs:59
   4: std::sys_common::backtrace::print
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libstd\sys_common\backtrace.rs:59
   5: std::panicking::default_hook
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libstd\panicking.rs:227
   6: std::panicking::rust_panic_with_hook
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libstd\panicking.rs:491
   7: std::panicking::continue_panic_fmt
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libstd\panicking.rs:398
   8: std::panicking::rust_begin_panic
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libstd\panicking.rs:325
   9: core::panicking::panic_fmt
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libcore\panicking.rs:95
  10: core::result::unwrap_failed<reqwest::error::Error>
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\src\libcore\macros.rs:26
  11: core::result::Result<lta::bus::bus_stops::BusStopsResp, reqwest::error::Error>::unwrap<lta::bus::bus_stops::BusStopsResp,reqwest::error::Error>
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\src\libcore\result.rs:808
  12: lta::bus::get_bus_stops
             at C:\Users\zeon000\.cargo\git\checkouts\lta-rs-f6ada22c85a9129d\add9969\src\bus.rs:331
  13: cratetest::main
             at .\src\main.rs:5
  14: std::rt::lang_start::{{closure}}<()>
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\src\libstd\rt.rs:74
  15: std::rt::lang_start_internal::{{closure}}
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libstd\rt.rs:59
  16: std::rt::lang_start_internal::{{closure}}
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libstd\rt.rs:59
  17: panic_unwind::__rust_maybe_catch_panic
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libpanic_unwind\lib.rs:102
  18: std::panicking::try
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libstd\panicking.rs:289
  19: std::panicking::try
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libstd\panicking.rs:289
  20: std::panicking::try
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libstd\panicking.rs:289
  21: std::rt::lang_start<()>
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\src\libstd\rt.rs:74
  22: main
  23: invoke_main
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  24: invoke_main
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  25: BaseThreadInitThunk
  26: RtlUserThreadStart
error: process didn't exit successfully: `target\debug\cratetest.exe` (exit code: 101)
```

Code
```rust
fn main() {
    match lta::bus::get_bus_stops() {
        Ok(t) => println!("{:?}", t),
        Err(e) => println!("{:?}", e)
    }

    match lta::bus::get_bus_services() {
        Ok(t) => println!("{:?}", t),
        Err(e) => println!("{:?}", e)
    }
}
```

**Comment by BudiNverse** [comment]
The problem with this code is, you have not set you API key. You can set your API key like this
```rust
fn main() {
    lta::client_config::CLIENT_CONFIG.lock().unwrap().with_api_key("api_key");
    match lta::bus::get_bus_stops() {
        Ok(t) => println!("{:?}", t),
        Err(e) => println!("{:?}", e)
    }

    match lta::bus::get_bus_services() {
        Ok(t) => println!("{:?}", t),
        Err(e) => println!("{:?}", e)
    }
}
```
