### ISSUE TITLE
I am getting API key not init!

### ISSUE THREAD

**Issue by BudiNverse** [BudiNverse/lta-rs#2]
Stacktrace
```
thread 'tests::get_arrivals' panicked at 'API key not init!', src\client_config.rs:34:21
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libstd\sys\windows\backtrace\mod.rs:104
   1: std::sys::windows::backtrace::set_frames
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libstd\sys\windows\backtrace\mod.rs:104
   2: std::sys::windows::backtrace::set_frames
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libstd\sys\windows\backtrace\mod.rs:104
   3: std::sys_common::backtrace::print
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libstd\sys_common\backtrace.rs:59
   4: std::sys_common::backtrace::print
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libstd\sys_common\backtrace.rs:59
   5: std::panicking::default_hook
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libstd\panicking.rs:221
   6: std::panicking::rust_panic_with_hook
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libstd\panicking.rs:491
   7: std::panicking::begin_panic<str*>
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\src\libstd\panicking.rs:425
   8: lta::client_config::ClientConfig::get_req_builder
             at .\src\client_config.rs:34
   9: lta::bus::get_arrival
             at .\src\bus.rs:121
  10: lta::tests::get_arrivals
             at .\src\lib.rs:28
  11: lta::tests::get_arrivals::{{closure}}
             at .\src\lib.rs:26
  12: core::ops::function::FnOnce::call_once<closure,()>
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\src\libcore\ops\function.rs:238
  13: test::run_test::{{closure}}
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libtest\lib.rs:1454
  14: test::run_test::{{closure}}
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libtest\lib.rs:1454
  15: test::run_test::{{closure}}
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libtest\lib.rs:1454
  16: panic_unwind::__rust_maybe_catch_panic
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libpanic_unwind\lib.rs:102
  17: std::panicking::try
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\src\libstd\panicking.rs:289
  18: std::panicking::try
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\src\libstd\panicking.rs:289
  19: std::panicking::try
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\src\libstd\panicking.rs:289
  20: std::panicking::try
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\src\libstd\panicking.rs:289
  21: std::thread::{{impl}}::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\src\libstd\thread\mod.rs:477
  22: std::thread::{{impl}}::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\src\libstd\thread\mod.rs:477
  23: std::thread::{{impl}}::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\src\libstd\thread\mod.rs:477
  24: panic_unwind::__rust_maybe_catch_panic
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\/src\libpanic_unwind\lib.rs:102
  25: std::panicking::try
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\src\libstd\panicking.rs:289
  26: std::panicking::try
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\src\libstd\panicking.rs:289
  27: std::panicking::try
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\src\libstd\panicking.rs:289
  28: std::panicking::try
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\src\libstd\panicking.rs:289
  29: alloc::boxed::{{impl}}::call_once
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\src\liballoc\boxed.rs:683
  30: alloc::boxed::{{impl}}::call_once
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\src\liballoc\boxed.rs:683
  31: alloc::boxed::{{impl}}::call_once
             at /rustc/b3af09205b9af6026453946feadfd78b61b7a9fc\src\liballoc\boxed.rs:683
  32: BaseThreadInitThunk
  33: RtlUserThreadStart
```

Code
```rust
fn main() {
    match lta::bus::get_arrival(83139, "15") {
        Ok(t) => println!("{:?}", t),
        Err(e) => println!("{:?}", e)
    }
}
```

**Comment by BudiNverse** [comment]
Make sure that you call `with_api_key("your key here")`
**Do note that if the key provided is empty ie `""`, your application will still panic.** 
If you do provide an illegitimate API key you will get [Issue #1 ](https://github.com/BudiNverse/lta-rs/issues/1)

Working Example
```rust
fn main() {
    lta::client_config::CLIENT_CONFIG.lock().unwrap().with_api_key("your key here");
    match lta::bus::get_arrival(83139, "15") {
        Ok(t) => println!("{:?}", t),
        Err(e) => println!("{:?}", e)
    }
}
```
